name: Simple Workflow

on:
  workflow_dispatch:
    inputs:
      var1:
        description: "var 1"
        required: true
        type: string

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run a Simple Command
        run: echo "Hello, GitHub Runner!"
      
      - name: read env
        env:
          resource_id: "resource_id_1234"
          resource_dir: "gcp"
        run: |
          if [ -d services/${resource_dir} ]; then
            echo "dir found"
          else
            echo "directory not found"
            exit 1;
          fi

