on:
  push:
    branches:
    - 'delete_*'
  pull_request:
    branches:
    - master

jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run simple command
        run: echo "Hello world"
    outputs:
      output1: "value of output1"

  my-second-job:
    name: second-job
    needs: my-job
    runs-on: self-hosted
    steps:
    - name: Read variable
      run: |
        echo ${{ secrets.GITHUB_TOKEN }}
        echo ${{ needs.my-job.outputs.output1 }}
    outputs:
      output1: ${{ needs.my-job.outputs.output1 }}
  # my-third-job:
  #   name: third-job
  #   needs: my-second-job
  #   runs-on: self-hosted
  #   steps:
  #   - name: Read from job1
  #     run: |
  #       echo ${{ needs.my-second-job.outputs.output1 }}
